version: '3.9'
services:
  java_app:
    container_name: java_app
    image: todolist-app:1.0.0
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=todolist
      - DB_SCHEMA=public
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=java_db
      - DB_PORT=5432
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
